import LegalDocumentLayout from '../components/LegalDocumentLayout';

function TermsOfServicePage() {
  return (
    <LegalDocumentLayout title="Terms of Service">
      <p>
        By accessing or using Talk to Folder (&quot;the Service&quot;), you
        agree to these Terms of Service. If you do not agree, do not use the
        Service.
      </p>

      <h2>Description of the Service</h2>
      <p>
        The Service lets you connect Google Drive, select folders, and chat with
        an assistant that uses content from those folders as context. Outputs
        are generated automatically and may be incomplete or incorrect.
      </p>

      <h2>Google Drive and your content</h2>
      <p>
        You are responsible for the folders you index and for ensuring you have
        the right to use that content with the Service. You grant us permission
        to access, process, and store information from folders you add, as
        described in our Privacy Policy.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service in violation of law or third-party rights.</li>
        <li>
          Attempt to access Drive data or systems you are not authorized to use.
        </li>
        <li>
          Probe, disrupt, or overload the Service or underlying infrastructure.
        </li>
        <li>
          Reverse engineer or circumvent security or usage limits except where
          prohibited law says otherwise.
        </li>
      </ul>

      <h2>AI outputs and reliance</h2>
      <p>
        Responses are generated by AI and are not professional, legal,
        financial, or medical advice. You are responsible for how you use
        outputs and for verifying important information from original sources.
      </p>

      <h2>Third parties</h2>
      <p>
        The Service relies on Google, hosting providers, databases, and AI
        vendors. Their services are subject to their own terms. Availability may
        depend on them.
      </p>

      <h2>Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;
        WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING
        IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, AND NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY LAW.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE AND OUR SUPPLIERS WILL NOT BE
        LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
        DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR OTHER INTANGIBLE
        LOSSES, ARISING FROM YOUR USE OF THE SERVICE. OUR AGGREGATE LIABILITY
        FOR CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A)
        THE AMOUNTS YOU PAID US FOR THE SERVICE IN THE TWELVE MONTHS BEFORE THE
        CLAIM OR (B) FIFTY U.S. DOLLARS, IF YOU HAVE NOT PAID US.
      </p>

      <h2>Indemnity</h2>
      <p>
        You will defend and indemnify us against claims, damages, losses, and
        expenses (including reasonable attorneys&apos; fees) arising from your
        use of the Service, your content, or your violation of these terms.
      </p>

      <h2>Suspension and termination</h2>
      <p>
        We may suspend or terminate access to the Service at any time, with or
        without notice, for conduct that we believe violates these terms or
        harms the Service or others.
      </p>

      <h2>Changes</h2>
      <p>
        We may modify these terms or the Service. Material changes will be
        indicated by updating the &quot;Last updated&quot; date on this page.
        Continued use after changes constitutes acceptance where allowed by law.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws applicable to the operator of this
        deployment, excluding conflict-of-law rules. Courts in that jurisdiction
        have exclusive venue unless mandatory consumer protections require
        otherwise.
      </p>

      <h2>Contact</h2>
      <p>
        For questions about these terms, use the contact method provided for
        this deployment of Talk to Folder.
      </p>
    </LegalDocumentLayout>
  );
}

export default TermsOfServicePage;
